
STATE.NAMES <-
    c(AP = 'Andhra Pradesh',
      AR = 'Arunachal Pradesh',
      AS = 'Assam',
      BR = 'Bihar',
      CT = 'Chhattisgarh',
      GA = 'Goa',
      GJ = 'Gujarat',
      HR = 'Haryana',
      HP = 'Himachal Pradesh',
      JH = 'Jharkhand',
      KA = 'Karnataka',
      KL = 'Kerala',
      MP = 'Madhya Pradesh',
      MH = 'Maharashtra',
      MN = 'Manipur',
      ML = 'Meghalaya',
      MZ = 'Mizoram',
      NL = 'Nagaland',
      OR = 'Odisha',
      PB = 'Punjab',
      RJ = 'Rajasthan',
      SK = 'Sikkim',
      TN = 'Tamil Nadu',
      TG = 'Telangana',
      TR = 'Tripura',
      UT = 'Uttarakhand',
      UP = 'Uttar Pradesh',
      WB = 'West Bengal',
      AN = 'Andaman and Nicobar Islands',
      CH = 'Chandigarh',
      DN = 'Dadra and Nagar Haveli and Daman and Diu',
      DL = 'Delhi',
      JK = 'Jammu and Kashmir',
      LA = 'Ladakh',
      LD = 'Lakshadweep',
      PY = 'Puducherry',
      TT = 'India')


## sort names by code to get desired order (to match covid19india.org)
STATE.NAMES <- STATE.NAMES[sort(names(STATE.NAMES))]

STATE.CODES <- names(STATE.NAMES)
names(STATE.CODES) <- STATE.NAMES

## CoWIN state and district codes

if (FALSE)
{
    stopifnot(require(jsonlite))

    cowin.states <-
        fromJSON("https://cdn-api.co-vin.in/api/v2/admin/location/states")$states
    stopifnot(is.data.frame(cowin.states))
    cowin.states <- within(cowin.states,
    {
        state_code <- STATE.CODES[state_name]
    })
    ## NOTE: 'Dadra and Nagar Haveli' and 'Daman and Diu' are listed separately.
    dput(cowin.states)

}

cowin.states <-
    data.frame(state_id = c(1L, 2L, 3L, 4L, 5L, 6L, 7L, 8L, 37L, 9L,
                            10L, 11L, 12L, 13L, 14L, 15L, 16L, 17L,
                            18L, 19L, 20L, 21L, 22L, 23L, 24L, 25L,
                            26L, 27L, 28L, 29L, 30L, 31L, 32L, 33L,
                            34L, 35L, 36L),
               state_name = c("Andaman and Nicobar Islands",
                              "Andhra Pradesh", "Arunachal Pradesh",
                              "Assam", "Bihar", "Chandigarh",
                              "Chhattisgarh",
                              "Dadra and Nagar Haveli",
                              "Daman and Diu", "Delhi", "Goa",
                              "Gujarat", "Haryana",
                              "Himachal Pradesh", "Jammu and Kashmir",
                              "Jharkhand", "Karnataka", "Kerala",
                              "Ladakh", "Lakshadweep",
                              "Madhya Pradesh", "Maharashtra",
                              "Manipur", "Meghalaya", "Mizoram",
                              "Nagaland", "Odisha", "Puducherry",
                              "Punjab", "Rajasthan", "Sikkim",
                              "Tamil Nadu", "Telangana", "Tripura",
                              "Uttar Pradesh", "Uttarakhand",
                              "West Bengal"),
               state_code = c("AN", "AP", "AR", "AS", "BR", "CH",
                              "CT", NA, NA, "DL", "GA", "GJ", "HR",
                              "HP", "JK", "JH", "KA", "KL", "LA",
                              "LD", "MP", "MH", "MN", "ML", "MZ",
                              "NL", "OR", "PY", "PB", "RJ", "SK",
                              "TN", "TG", "TR", "UP", "UT", "WB"))


if (FALSE)
{
    ## make sure state id's start from one and always increase by 1
    stopifnot(min(cowin.states$state_id) == 1)
    stopifnot(all(diff(sort(cowin.states$state_id)) == 1))

    nstates <- max(cowin.states$state_id)

    cowin.districts <- 
        lapply(seq_len(nstates),
               function(n) {
                   URL <- sprintf("https://cdn-api.co-vin.in/api/v2/admin/location/districts/%d", n)
                   fromJSON(URL)$districts
               })
    names(cowin.districts) <- as.character(seq_len(nstates))
    cowin.districts <- do.call(lattice::make.groups, cowin.districts)
    cowin.districts <- within(cowin.districts,
    {
        state_id  <- as.numeric(which)
        rm(which)
    })
    row.names(cowin.districts) <- NULL
    dput(cowin.districts)
    
}

cowin.districts <-
    data.frame(state_id = c(1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
                            2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
                            3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
                            4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
                            4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
                            4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5,
                            5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
                            5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
                            5, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
                            7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
                            7, 7, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
                            10, 10, 11, 11, 11, 11, 11, 11, 11, 11,
                            11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
                            11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
                            11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
                            11, 11, 11, 12, 12, 12, 12, 12, 12, 12,
                            12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
                            12, 12, 12, 12, 12, 13, 13, 13, 13, 13,
                            13, 13, 13, 13, 13, 13, 13, 14, 14, 14,
                            14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
                            14, 14, 14, 14, 14, 14, 14, 15, 15, 15,
                            15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
                            15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
                            15, 16, 16, 16, 16, 16, 16, 16, 16, 16,
                            16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
                            16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
                            16, 16, 17, 17, 17, 17, 17, 17, 17, 17,
                            17, 17, 17, 17, 17, 17, 18, 18, 19, 19,
                            20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
                            20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
                            20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
                            20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
                            20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
                            20, 21, 21, 21, 21, 21, 21, 21, 21, 21,
                            21, 21, 21, 21, 21, 21, 21, 21, 21, 21,
                            21, 21, 21, 21, 21, 21, 21, 21, 21, 21,
                            21, 21, 21, 21, 21, 21, 22, 22, 22, 22,
                            22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
                            22, 22, 23, 23, 23, 23, 23, 23, 23, 23,
                            23, 23, 23, 24, 24, 24, 24, 24, 24, 24,
                            24, 24, 25, 25, 25, 25, 25, 25, 25, 25,
                            25, 25, 25, 26, 26, 26, 26, 26, 26, 26,
                            26, 26, 26, 26, 26, 26, 26, 26, 26, 26,
                            26, 26, 26, 26, 26, 26, 26, 26, 26, 26,
                            26, 26, 26, 27, 27, 27, 27, 28, 28, 28,
                            28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
                            28, 28, 28, 28, 28, 28, 28, 28, 28, 29,
                            29, 29, 29, 29, 29, 29, 29, 29, 29, 29,
                            29, 29, 29, 29, 29, 29, 29, 29, 29, 29,
                            29, 29, 29, 29, 29, 29, 29, 29, 29, 29,
                            29, 29, 29, 30, 30, 30, 30, 31, 31, 31,
                            31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
                            31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
                            31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
                            31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
                            31, 31, 32, 32, 32, 32, 32, 32, 32, 32,
                            32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
                            32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
                            32, 32, 32, 32, 32, 33, 33, 33, 33, 33,
                            33, 33, 33, 34, 34, 34, 34, 34, 34, 34,
                            34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
                            34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
                            34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
                            34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
                            34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
                            34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
                            34, 34, 34, 34, 34, 34, 34, 34, 35, 35,
                            35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
                            35, 36, 36, 36, 36, 36, 36, 36, 36, 36,
                            36, 36, 36, 36, 36, 36, 36, 36, 36, 36,
                            36, 36, 36, 36, 36, 36, 36, 36, 36, 36,
                            37, 37),

               district_id = c(3L, 1L, 2L, 9L, 10L, 11L, 5L, 4L, 7L,
                               12L, 13L, 14L, 8L, 15L, 16L, 6L, 22L,
                               20L, 25L, 23L, 42L, 17L, 24L, 27L, 21L,
                               33L, 29L, 40L, 31L, 18L, 32L, 36L, 19L,
                               39L, 35L, 37L, 30L, 26L, 34L, 41L, 28L,
                               38L, 46L, 47L, 765L, 57L, 66L, 766L,
                               58L, 48L, 62L, 59L, 43L, 67L, 60L, 53L,
                               68L, 764L, 54L, 49L, 50L, 51L, 69L,
                               61L, 63L, 767L, 55L, 56L, 52L, 44L,
                               64L, 768L, 45L, 65L, 769L, 74L, 78L,
                               77L, 83L, 98L, 82L, 99L, 100L, 94L,
                               105L, 79L, 104L, 107L, 91L, 80L, 75L,
                               101L, 76L, 84L, 70L, 95L, 85L, 86L,
                               90L, 92L, 97L, 73L, 81L, 71L, 96L,
                               102L, 93L, 87L, 88L, 103L, 72L, 89L,
                               106L, 108L, 110L, 111L, 112L, 113L,
                               114L, 115L, 116L, 117L, 118L, 119L,
                               120L, 136L, 121L, 122L, 123L, 135L,
                               124L, 125L, 126L, 127L, 128L, 129L,
                               130L, 109L, 131L, 132L, 133L, 134L,
                               137L, 141L, 145L, 140L, 146L, 147L,
                               143L, 148L, 149L, 144L, 150L, 142L,
                               151L, 152L, 154L, 770L, 174L, 179L,
                               158L, 159L, 180L, 175L, 771L, 176L,
                               181L, 182L, 163L, 168L, 153L, 772L,
                               177L, 169L, 773L, 178L, 774L, 156L,
                               170L, 183L, 160L, 171L, 184L, 164L,
                               185L, 161L, 172L, 173L, 775L, 162L,
                               165L, 776L, 157L, 166L, 155L, 777L,
                               167L, 193L, 200L, 201L, 199L, 196L,
                               188L, 191L, 189L, 204L, 190L, 203L,
                               186L, 206L, 205L, 207L, 187L, 195L,
                               202L, 192L, 194L, 198L, 197L, 219L,
                               214L, 217L, 213L, 216L, 211L, 210L,
                               215L, 208L, 212L, 209L, 218L, 224L,
                               223L, 225L, 229L, 232L, 228L, 230L,
                               234L, 231L, 221L, 226L, 238L, 227L,
                               237L, 235L, 239L, 236L, 222L, 220L,
                               233L, 242L, 245L, 253L, 257L, 258L,
                               247L, 243L, 256L, 262L, 251L, 255L,
                               259L, 252L, 241L, 244L, 250L, 261L,
                               246L, 254L, 240L, 260L, 248L, 249L,
                               263L, 270L, 276L, 265L, 294L, 264L,
                               274L, 272L, 271L, 273L, 291L, 268L,
                               269L, 275L, 278L, 280L, 267L, 289L,
                               279L, 283L, 277L, 282L, 290L, 266L,
                               284L, 292L, 287L, 288L, 286L, 281L,
                               293L, 285L, 301L, 307L, 306L, 297L,
                               295L, 298L, 304L, 305L, 302L, 308L,
                               300L, 296L, 303L, 299L, 309L, 310L,
                               796L, 311L, 320L, 357L, 334L, 354L,
                               338L, 343L, 362L, 351L, 312L, 342L,
                               328L, 337L, 327L, 350L, 324L, 341L,
                               336L, 348L, 313L, 361L, 360L, 314L,
                               315L, 340L, 353L, 339L, 344L, 335L,
                               319L, 347L, 352L, 323L, 326L, 359L,
                               358L, 322L, 316L, 317L, 333L, 356L,
                               349L, 332L, 321L, 346L, 345L, 331L,
                               330L, 325L, 318L, 329L, 355L, 391L,
                               364L, 366L, 397L, 384L, 370L, 367L,
                               380L, 388L, 379L, 378L, 386L, 390L,
                               396L, 371L, 383L, 395L, 365L, 382L,
                               387L, 389L, 381L, 394L, 385L, 363L,
                               393L, 372L, 373L, 376L, 374L, 375L,
                               392L, 377L, 369L, 368L, 398L, 399L,
                               400L, 401L, 402L, 410L, 413L, 409L,
                               408L, 412L, 411L, 403L, 404L, 407L,
                               405L, 406L, 424L, 418L, 414L, 423L,
                               417L, 421L, 422L, 415L, 420L, 416L,
                               419L, 425L, 426L, 429L, 428L, 432L,
                               431L, 427L, 430L, 433L, 434L, 444L,
                               441L, 438L, 437L, 439L, 435L, 443L,
                               440L, 436L, 442L, 445L, 448L, 447L,
                               472L, 454L, 468L, 457L, 473L, 458L,
                               467L, 449L, 459L, 460L, 474L, 464L,
                               450L, 461L, 455L, 446L, 451L, 469L,
                               456L, 470L, 462L, 465L, 463L, 471L,
                               452L, 466L, 453L, 476L, 477L, 475L,
                               478L, 485L, 483L, 493L, 499L, 484L,
                               487L, 480L, 489L, 481L, 492L, 479L,
                               488L, 482L, 491L, 486L, 494L, 497L,
                               498L, 496L, 500L, 490L, 495L, 507L,
                               512L, 519L, 516L, 528L, 508L, 523L,
                               501L, 514L, 521L, 530L, 511L, 524L,
                               520L, 517L, 505L, 506L, 527L, 533L,
                               515L, 510L, 502L, 525L, 503L, 532L,
                               529L, 522L, 518L, 534L, 513L, 531L,
                               509L, 526L, 504L, 535L, 537L, 538L,
                               536L, 779L, 555L, 578L, 565L, 571L,
                               778L, 539L, 547L, 566L, 556L, 563L,
                               552L, 557L, 544L, 559L, 780L, 562L,
                               540L, 576L, 558L, 577L, 564L, 573L,
                               570L, 575L, 546L, 567L, 781L, 545L,
                               561L, 580L, 551L, 541L, 569L, 554L,
                               560L, 548L, 550L, 568L, 572L, 553L,
                               574L, 543L, 542L, 549L, 582L, 583L,
                               581L, 584L, 585L, 586L, 587L, 588L,
                               589L, 590L, 591L, 592L, 593L, 594L,
                               595L, 596L, 612L, 597L, 598L, 613L,
                               599L, 600L, 601L, 602L, 603L, 604L,
                               605L, 606L, 607L, 608L, 609L, 610L,
                               611L, 614L, 615L, 616L, 617L, 618L,
                               619L, 620L, 621L, 622L, 623L, 625L,
                               626L, 627L, 628L, 646L, 629L, 630L,
                               631L, 632L, 633L, 634L, 635L, 636L,
                               637L, 638L, 687L, 639L, 640L, 641L,
                               642L, 643L, 644L, 645L, 647L, 648L,
                               649L, 650L, 651L, 652L, 653L, 654L,
                               655L, 656L, 657L, 658L, 659L, 660L,
                               661L, 662L, 663L, 664L, 665L, 666L,
                               667L, 668L, 669L, 670L, 671L, 672L,
                               673L, 674L, 675L, 676L, 677L, 678L,
                               679L, 680L, 682L, 624L, 681L, 683L,
                               684L, 685L, 686L, 688L, 689L, 690L,
                               691L, 692L, 693L, 694L, 695L, 696L,
                               704L, 707L, 699L, 708L, 697L, 702L,
                               709L, 698L, 706L, 700L, 701L, 705L,
                               703L, 710L, 711L, 712L, 713L, 714L,
                               715L, 783L, 716L, 717L, 718L, 719L,
                               720L, 721L, 722L, 723L, 724L, 725L,
                               726L, 727L, 728L, 729L, 730L, 731L,
                               732L, 733L, 734L, 735L, 736L, 737L,
                               138L, 139L),

               district_name = c("Nicobar",
                                 "North and Middle Andaman",
                                 "South Andaman", "Anantapur",
                                 "Chittoor", "East Godavari",
                                 "Guntur", "Krishna", "Kurnool",
                                 "Prakasam",
                                 "Sri Potti Sriramulu Nellore",
                                 "Srikakulam", "Visakhapatnam",
                                 "Vizianagaram", "West Godavari",
                                 "YSR District, Kadapa (Cuddapah)",
                                 "Anjaw", "Changlang",
                                 "Dibang Valley", "East Kameng",
                                 "East Siang",
                                 "Itanagar Capital Complex", "Kamle",
                                 "Kra Daadi", "Kurung Kumey",
                                 "Lepa Rada", "Lohit", "Longding",
                                 "Lower Dibang Valley", "Lower Siang",
                                 "Lower Subansiri", "Namsai",
                                 "Pakke Kessang", "Papum Pare",
                                 "Shi Yomi", "Siang", "Tawang",
                                 "Tirap", "Upper Siang",
                                 "Upper Subansiri", "West Kameng",
                                 "West Siang", "Baksa", "Barpeta",
                                 "Biswanath", "Bongaigaon", "Cachar",
                                 "Charaideo", "Chirang", "Darrang",
                                 "Dhemaji", "Dhubri", "Dibrugarh",
                                 "Dima Hasao", "Goalpara", "Golaghat",
                                 "Hailakandi", "Hojai", "Jorhat",
                                 "Kamrup Metropolitan",
                                 "Kamrup Rural", "Karbi-Anglong",
                                 "Karimganj", "Kokrajhar",
                                 "Lakhimpur", "Majuli", "Morigaon",
                                 "Nagaon", "Nalbari", "Sivasagar",
                                 "Sonitpur",
                                 "South Salmara Mankachar",
                                 "Tinsukia", "Udalguri",
                                 "West Karbi Anglong", "Araria",
                                 "Arwal", "Aurangabad", "Banka",
                                 "Begusarai", "Bhagalpur", "Bhojpur",
                                 "Buxar", "Darbhanga",
                                 "East Champaran", "Gaya",
                                 "Gopalganj", "Jamui", "Jehanabad",
                                 "Kaimur", "Katihar", "Khagaria",
                                 "Kishanganj", "Lakhisarai",
                                 "Madhepura", "Madhubani", "Munger",
                                 "Muzaffarpur", "Nalanda", "Nawada",
                                 "Patna", "Purnia", "Rohtas",
                                 "Saharsa", "Samastipur", "Saran",
                                 "Sheikhpura", "Sheohar", "Sitamarhi",
                                 "Siwan", "Supaul", "Vaishali",
                                 "West Champaran", "Chandigarh",
                                 "Balod", "Baloda bazar", "Balrampur",
                                 "Bastar", "Bemetara", "Bijapur",
                                 "Bilaspur", "Dantewada", "Dhamtari",
                                 "Durg", "Gariaband",
                                 "Gaurela Pendra Marwahi ",
                                 "Janjgir-Champa", "Jashpur",
                                 "Kanker", "Kawardha", "Kondagaon",
                                 "Korba", "Koriya", "Mahasamund",
                                 "Mungeli", "Narayanpur", "Raigarh",
                                 "Raipur", "Rajnandgaon", "Sukma",
                                 "Surajpur", "Surguja",
                                 "Dadra and Nagar Haveli",
                                 "Central Delhi", "East Delhi",
                                 "New Delhi", "North Delhi",
                                 "North East Delhi",
                                 "North West Delhi", "Shahdara",
                                 "South Delhi", "South East Delhi",
                                 "South West Delhi", "West Delhi",
                                 "North Goa", "South Goa",
                                 "Ahmedabad", "Ahmedabad Corporation",
                                 "Amreli", "Anand", "Aravalli",
                                 "Banaskantha", "Bharuch",
                                 "Bhavnagar", "Bhavnagar Corporation",
                                 "Botad", "Chhotaudepur", "Dahod",
                                 "Dang", "Devbhumi Dwaraka",
                                 "Gandhinagar",
                                 "Gandhinagar Corporation",
                                 "Gir Somnath", "Jamnagar",
                                 "Jamnagar Corporation", "Junagadh",
                                 "Junagadh Corporation", "Kheda",
                                 "Kutch", "Mahisagar", "Mehsana",
                                 "Morbi", "Narmada", "Navsari",
                                 "Panchmahal", "Patan", "Porbandar",
                                 "Rajkot", "Rajkot Corporation",
                                 "Sabarkantha", "Surat",
                                 "Surat Corporation", "Surendranagar",
                                 "Tapi", "Vadodara",
                                 "Vadodara Corporation", "Valsad",
                                 "Ambala", "Bhiwani", "Charkhi Dadri",
                                 "Faridabad", "Fatehabad", "Gurgaon",
                                 "Hisar", "Jhajjar", "Jind",
                                 "Kaithal", "Karnal", "Kurukshetra",
                                 "Mahendragarh", "Nuh", "Palwal",
                                 "Panchkula", "Panipat", "Rewari",
                                 "Rohtak", "Sirsa", "Sonipat",
                                 "Yamunanagar", "Bilaspur", "Chamba",
                                 "Hamirpur", "Kangra", "Kinnaur",
                                 "Kullu", "Lahaul Spiti", "Mandi",
                                 "Shimla", "Sirmaur", "Solan", "Una",
                                 "Anantnag", "Bandipore", "Baramulla",
                                 "Budgam", "Doda", "Ganderbal",
                                 "Jammu", "Kathua", "Kishtwar",
                                 "Kulgam", "Kupwara", "Poonch",
                                 "Pulwama", "Rajouri", "Ramban",
                                 "Reasi", "Samba", "Shopian",
                                 "Srinagar", "Udhampur", "Bokaro",
                                 "Chatra", "Deoghar", "Dhanbad",
                                 "Dumka", "East Singhbhum", "Garhwa",
                                 "Giridih", "Godda", "Gumla",
                                 "Hazaribagh", "Jamtara", "Khunti",
                                 "Koderma", "Latehar", "Lohardaga",
                                 "Pakur", "Palamu", "Ramgarh",
                                 "Ranchi", "Sahebganj",
                                 "Seraikela Kharsawan", "Simdega",
                                 "West Singhbhum", "Bagalkot",
                                 "Bangalore Rural", "Bangalore Urban",
                                 "BBMP", "Belgaum", "Bellary",
                                 "Bidar", "Chamarajanagar",
                                 "Chikamagalur", "Chikkaballapur",
                                 "Chitradurga", "Dakshina Kannada",
                                 "Davanagere", "Dharwad", "Gadag",
                                 "Gulbarga", "Hassan", "Haveri",
                                 "Kodagu", "Kolar", "Koppal",
                                 "Mandya", "Mysore", "Raichur",
                                 "Ramanagara", "Shimoga", "Tumkur",
                                 "Udupi", "Uttar Kannada",
                                 "Vijayapura", "Yadgir", "Alappuzha",
                                 "Ernakulam", "Idukki", "Kannur",
                                 "Kasaragod", "Kollam", "Kottayam",
                                 "Kozhikode", "Malappuram",
                                 "Palakkad", "Pathanamthitta",
                                 "Thiruvananthapuram", "Thrissur",
                                 "Wayanad", "Kargil", "Leh",
                                 "Agatti Island", "Lakshadweep",
                                 "Agar", "Alirajpur", "Anuppur",
                                 "Ashoknagar", "Balaghat", "Barwani",
                                 "Betul", "Bhind", "Bhopal",
                                 "Burhanpur", "Chhatarpur",
                                 "Chhindwara", "Damoh", "Datia",
                                 "Dewas", "Dhar", "Dindori", "Guna",
                                 "Gwalior", "Harda", "Hoshangabad",
                                 "Indore", "Jabalpur", "Jhabua",
                                 "Katni", "Khandwa", "Khargone",
                                 "Mandla", "Mandsaur", "Morena",
                                 "Narsinghpur", "Neemuch", "Panna",
                                 "Raisen", "Rajgarh", "Ratlam",
                                 "Rewa", "Sagar", "Satna", "Sehore",
                                 "Seoni", "Shahdol", "Shajapur",
                                 "Sheopur", "Shivpuri", "Sidhi",
                                 "Singrauli", "Tikamgarh", "Ujjain",
                                 "Umaria", "Vidisha", "Ahmednagar",
                                 "Akola", "Amravati", "Aurangabad ",
                                 "Beed", "Bhandara", "Buldhana",
                                 "Chandrapur", "Dhule", "Gadchiroli",
                                 "Gondia", "Hingoli", "Jalgaon",
                                 "Jalna", "Kolhapur", "Latur",
                                 "Mumbai", "Nagpur", "Nanded",
                                 "Nandurbar", "Nashik", "Osmanabad",
                                 "Palghar", "Parbhani", "Pune",
                                 "Raigad", "Ratnagiri", "Sangli",
                                 "Satara", "Sindhudurg", "Solapur",
                                 "Thane", "Wardha", "Washim",
                                 "Yavatmal", "Bishnupur", "Chandel",
                                 "Churachandpur", "Imphal East",
                                 "Imphal West", "Jiribam", "Kakching",
                                 "Kamjong", "Kangpokpi", "Noney",
                                 "Pherzawl", "Senapati", "Tamenglong",
                                 "Tengnoupal", "Thoubal", "Ukhrul",
                                 "East Garo Hills",
                                 "East Jaintia Hills",
                                 "East Khasi Hills",
                                 "North Garo Hills", "Ri-Bhoi",
                                 "South Garo Hills",
                                 "South West Garo Hills",
                                 "South West Khasi Hills",
                                 "West Garo Hills",
                                 "West Jaintia Hills",
                                 "West Khasi Hills", "Aizawl East",
                                 "Aizawl West", "Champhai", "Kolasib",
                                 "Lawngtlai", "Lunglei", "Mamit",
                                 "Serchhip", "Siaha", "Dimapur",
                                 "Kiphire", "Kohima", "Longleng",
                                 "Mokokchung", "Mon", "Peren", "Phek",
                                 "Tuensang", "Wokha", "Zunheboto",
                                 "Angul", "Balangir", "Balasore",
                                 "Bargarh", "Bhadrak", "Boudh",
                                 "Cuttack", "Deogarh", "Dhenkanal",
                                 "Gajapati", "Ganjam",
                                 "Jagatsinghpur", "Jajpur",
                                 "Jharsuguda", "Kalahandi",
                                 "Kandhamal", "Kendrapara",
                                 "Kendujhar", "Khurda", "Koraput",
                                 "Malkangiri", "Mayurbhanj",
                                 "Nabarangpur", "Nayagarh", "Nuapada",
                                 "Puri", "Rayagada", "Sambalpur",
                                 "Subarnapur", "Sundargarh",
                                 "Karaikal", "Mahe", "Puducherry",
                                 "Yanam", "Amritsar", "Barnala",
                                 "Bathinda", "Faridkot",
                                 "Fatehgarh Sahib", "Fazilka",
                                 "Ferozpur", "Gurdaspur",
                                 "Hoshiarpur", "Jalandhar",
                                 "Kapurthala", "Ludhiana", "Mansa",
                                 "Moga", "Pathankot", "Patiala",
                                 "Rup Nagar", "Sangrur", "SAS Nagar",
                                 "SBS Nagar", "Sri Muktsar Sahib",
                                 "Tarn Taran", "Ajmer", "Alwar",
                                 "Banswara", "Baran", "Barmer",
                                 "Bharatpur", "Bhilwara", "Bikaner",
                                 "Bundi", "Chittorgarh", "Churu",
                                 "Dausa", "Dholpur", "Dungarpur",
                                 "Hanumangarh", "Jaipur I",
                                 "Jaipur II", "Jaisalmer", "Jalore",
                                 "Jhalawar", "Jhunjhunu", "Jodhpur",
                                 "Karauli", "Kota", "Nagaur", "Pali",
                                 "Pratapgarh", "Rajsamand",
                                 "Sawai Madhopur", "Sikar", "Sirohi",
                                 "Sri Ganganagar", "Tonk", "Udaipur",
                                 "East Sikkim", "North Sikkim",
                                 "South Sikkim", "West Sikkim",
                                 "Aranthangi", "Ariyalur", "Attur",
                                 "Chengalpet", "Chennai", "Cheyyar",
                                 "Coimbatore", "Cuddalore",
                                 "Dharmapuri", "Dindigul", "Erode",
                                 "Kallakurichi", "Kanchipuram",
                                 "Kanyakumari", "Karur", "Kovilpatti",
                                 "Krishnagiri", "Madurai",
                                 "Nagapattinam", "Namakkal",
                                 "Nilgiris", "Palani", "Paramakudi",
                                 "Perambalur", "Poonamallee",
                                 "Pudukkottai", "Ramanathapuram",
                                 "Ranipet", "Salem", "Sivaganga",
                                 "Sivakasi", "Tenkasi", "Thanjavur",
                                 "Theni", "Thoothukudi (Tuticorin)",
                                 "Tiruchirappalli", "Tirunelveli",
                                 "Tirupattur", "Tiruppur",
                                 "Tiruvallur", "Tiruvannamalai",
                                 "Tiruvarur", "Vellore", "Viluppuram",
                                 "Virudhunagar", "Adilabad",
                                 "Bhadradri Kothagudem", "Hyderabad",
                                 "Jagtial", "Jangaon",
                                 "Jayashankar Bhupalpally",
                                 "Jogulamba Gadwal", "Kamareddy",
                                 "Karimnagar", "Khammam",
                                 "Kumuram Bheem", "Mahabubabad",
                                 "Mahabubnagar", "Mancherial",
                                 "Medak", "Medchal", "Mulugu",
                                 "Nagarkurnool", "Nalgonda",
                                 "Narayanpet", "Nirmal", "Nizamabad",
                                 "Peddapalli", "Rajanna Sircilla",
                                 "Rangareddy", "Sangareddy",
                                 "Siddipet", "Suryapet", "Vikarabad",
                                 "Wanaparthy", "Warangal(Rural)",
                                 "Warangal(Urban)",
                                 "Yadadri Bhuvanagiri", "Dhalai",
                                 "Gomati", "Khowai", "North Tripura",
                                 "Sepahijala", "South Tripura",
                                 "Unakoti", "West Tripura", "Agra",
                                 "Aligarh", "Ambedkar Nagar",
                                 "Amethi", "Amroha", "Auraiya",
                                 "Ayodhya", "Azamgarh", "Badaun",
                                 "Baghpat", "Bahraich", "Balarampur",
                                 "Ballia", "Banda", "Barabanki",
                                 "Bareilly", "Basti", "Bhadohi",
                                 "Bijnour", "Bulandshahr",
                                 "Chandauli", "Chitrakoot", "Deoria",
                                 "Etah", "Etawah", "Farrukhabad",
                                 "Fatehpur", "Firozabad",
                                 "Gautam Buddha Nagar", "Ghaziabad",
                                 "Ghazipur", "Gonda", "Gorakhpur",
                                 "Hamirpur", "Hapur", "Hardoi",
                                 "Hathras", "Jalaun", "Jaunpur",
                                 "Jhansi", "Kannauj", "Kanpur Dehat",
                                 "Kanpur Nagar", "Kasganj",
                                 "Kaushambi", "Kushinagar",
                                 "Lakhimpur Kheri", "Lalitpur",
                                 "Lucknow", "Maharajganj", "Mahoba",
                                 "Mainpuri", "Mathura", "Mau",
                                 "Meerut", "Mirzapur", "Moradabad",
                                 "Muzaffarnagar", "Pilibhit",
                                 "Pratapgarh", "Prayagraj",
                                 "Raebareli", "Rampur", "Saharanpur",
                                 "Sambhal", "Sant Kabir Nagar",
                                 "Shahjahanpur", "Shamli",
                                 "Shravasti", "Siddharthnagar",
                                 "Sitapur", "Sonbhadra", "Sultanpur",
                                 "Unnao", "Varanasi", "Almora",
                                 "Bageshwar", "Chamoli", "Champawat",
                                 "Dehradun", "Haridwar", "Nainital",
                                 "Pauri Garhwal", "Pithoragarh",
                                 "Rudraprayag", "Tehri Garhwal",
                                 "Udham Singh Nagar", "Uttarkashi",
                                 "Alipurduar District", "Bankura",
                                 "Basirhat HD (North 24 Parganas)",
                                 "Birbhum", "Bishnupur HD (Bankura)",
                                 "Cooch Behar", "COOCHBEHAR",
                                 "Dakshin Dinajpur", "Darjeeling",
                                 "Diamond Harbor HD (S 24 Parganas)",
                                 "East Bardhaman", "Hoogly", "Howrah",
                                 "Jalpaiguri", "Jhargram",
                                 "Kalimpong", "Kolkata", "Malda",
                                 "Murshidabad", "Nadia",
                                 "Nandigram HD (East Medinipore)",
                                 "North 24 Parganas",
                                 "Paschim Medinipore",
                                 "Purba Medinipore", "Purulia",
                                 "Rampurhat HD (Birbhum)",
                                 "South 24 Parganas",
                                 "Uttar Dinajpur", "West Bardhaman",
                                 "Daman", "Diu"))

